language: php

sudo: false

php:
    - 7.1
    - 7.0
    - 5.6
    - 5.5
#    - 5.4
    - hhvm

notifications:
    email: deploy@peter-gribanov.ru

matrix:
    fast_finish: true
    include:
        - php: 5.5
          env: COVERAGE=1
        - php: 7.1
          env:
            - BENCHMARK_ENUM_RIVAL=1
            - STOPWATCH_VERSION=~2.3|~3.0
            - MYCLABS_VERSION=~1.5
            - MARC_MAB_VERSION=~2.3
            - HAPPY_TYPES_VERSION=~1.0
        - php: 7.0
          env:
            - BENCHMARK_ENUM_RIVAL=1
            - STOPWATCH_VERSION=~2.3|~3.0
            - MYCLABS_VERSION=~1.5
            - MARC_MAB_VERSION=~2.3
            - HAPPY_TYPES_VERSION=~1.0
        - php: 5.6
          env:
            - BENCHMARK_ENUM_RIVAL=1
            - STOPWATCH_VERSION=~2.3|~3.0
            - MYCLABS_VERSION=~1.5
            - MARC_MAB_VERSION=~2.3
            - HAPPY_TYPES_VERSION=~1.0
        - php: 5.5
          env:
            - BENCHMARK_ENUM_RIVAL=1
            - STOPWATCH_VERSION=~2.3|~3.0
            - MYCLABS_VERSION=~1.5
            - MARC_MAB_VERSION=~2.3
            - HAPPY_TYPES_VERSION=~1.0
#        - php: 5.4
#          env:
#            - BENCHMARK_ENUM_RIVAL=1
#            - STOPWATCH_VERSION=~2.3|~3.0
#            - MYCLABS_VERSION=~1.5
#            - MARC_MAB_VERSION=~2.3
#            - HAPPY_TYPES_VERSION=~1.0
    allow_failures:
        - php: hhvm

before_install:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$COVERAGE" != "1" ]; then phpenv config-rm xdebug.ini; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - composer self-update

before_script:
    - if [ "$BENCHMARK_ENUM_RIVAL" == "1" ]; then composer require "symfony/stopwatch${STOPWATCH_VERSION}" --dev --no-update; fi;
    - if [ "$BENCHMARK_ENUM_RIVAL" == "1" ]; then composer require "myclabs/php-enum:${MYCLABS_VERSION}" --dev --no-update; fi;
    - if [ "$BENCHMARK_ENUM_RIVAL" == "1" ]; then composer require "marc-mabe/php-enum:${MARC_MAB_VERSION}" --dev --no-update; fi;
    - if [ "$BENCHMARK_ENUM_RIVAL" == "1" ]; then composer require "happy-types/enumerable-type:${HAPPY_TYPES_VERSION}" --dev --no-update; fi;
    - composer install --prefer-dist --no-interaction --no-scripts --no-progress

script:
    - if [ "$COVERAGE" != "1" ]; then vendor/bin/phpunit; fi;
    - if [ "$COVERAGE" == "1" ]; then vendor/bin/phpunit --coverage-clover build/coverage-clover.xml; fi;
    - if [ "$BENCHMARK_ENUM_RIVAL" == "1" ]; then php tests/benchmark/enum_rival.php 100000; fi;

after_script:
    - if [ "$COVERAGE" == "1" ]; then vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage-clover.xml; fi;
    - if [ "$COVERAGE" == "1" ]; then vendor/bin/coveralls -v -c .coveralls.yml; fi;
