language: php

sudo: false

notifications:
    email: deploy@peter-gribanov.ru

branches:
    except:
        - /^analysis-.*$/

matrix:
    fast_finish: true
    include:
        - php: 7.4
        - php: 7.3
        - php: 7.2
        - php: 7.1
        - php: 7.0
        - php: 5.6
        - php: 5.5
          dist: trusty

before_install:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

before_script:
    - COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction --no-scripts --no-progress

script:
    - vendor/bin/phpunit --verbose --coverage-clover build/coverage-clover.xml
    - php tests/benchmark/set.php 100000
    - php tests/benchmark/enum.php 100000

after_script:
    - vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage-clover.xml
    - vendor/bin/coveralls -v -c .coveralls.yml
